name: MacOS X (Cocoa) build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        true

    - name: generate makefile
      run: cmake -DCMAKE_BUILD_TYPE=Release -DFREEGLUT_BUILD_DEMOS=ON -DFREEGLUT_COCOA=ON .

    - name: build freeglut
      run: make

    - name: stage install
      run: DESTDIR=freeglut-instdir make install

    - uses: actions/upload-artifact@v4
      with:
        name: freeglut-instdir
        path: freeglut-instdir

# vi:ts=2 sts=2 sw=2 expandtab:
