/*
 * fg_stroke_mono_roman.c
 *
 * freeglut Monospace Roman stroke font definition
 *
 * Copyright (c) 1999-2000 Pawel W. Olszta. All Rights Reserved.
 * Written by Pawel W. Olszta, <olszta@sourceforge.net>
 * Creation date: Thu Dec 16 1999
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * PAWEL W. OLSZTA BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */


/* This file has been automatically generated by the genstroke utility. */

#include <GL/freeglut.h>
#include "fg_internal.h"

/* char: 0x20 */

static const SFG_StrokeStrip StrokeMonoRoman_ch32st[] =
{
  { 0, NULL }
};

static const SFG_StrokeChar StrokeMonoRoman_ch32 = {104.762f,0,StrokeMonoRoman_ch32st};

/* char: 0x21 */

static const SFG_StrokeVertex StrokeMonoRoman_ch33st0[] =
{
 {52.381f,100.0f},
 {52.381f,33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch33st1[] =
{
 {52.381f,9.5238f},
 {47.6191f,4.7619f},
 {52.381f,0.0f},
 {57.1429f,4.7619f},
 {52.381f,9.5238f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch33st[] =
{
 {2,StrokeMonoRoman_ch33st0},
 {5,StrokeMonoRoman_ch33st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch33 = {104.762f,2,StrokeMonoRoman_ch33st};

/* char: 0x22 */

static const SFG_StrokeVertex StrokeMonoRoman_ch34st0[] =
{
 {33.3334f,100.0f},
 {33.3334f,66.6667f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch34st1[] =
{
 {71.4286f,100.0f},
 {71.4286f,66.6667f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch34st[] =
{
 {2,StrokeMonoRoman_ch34st0},
 {2,StrokeMonoRoman_ch34st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch34 = {104.762f,2,StrokeMonoRoman_ch34st};

/* char: 0x23 */

static const SFG_StrokeVertex StrokeMonoRoman_ch35st0[] =
{
 {54.7619f,119.048f},
 {21.4286f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch35st1[] =
{
 {83.3334f,119.048f},
 {50.0f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch35st2[] =
{
 {21.4286f,57.1429f},
 {88.0952f,57.1429f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch35st3[] =
{
 {16.6667f,28.5714f},
 {83.3334f,28.5714f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch35st[] =
{
 {2,StrokeMonoRoman_ch35st0},
 {2,StrokeMonoRoman_ch35st1},
 {2,StrokeMonoRoman_ch35st2},
 {2,StrokeMonoRoman_ch35st3}
};

static const SFG_StrokeChar StrokeMonoRoman_ch35 = {104.762f,4,StrokeMonoRoman_ch35st};

/* char: 0x24 */

static const SFG_StrokeVertex StrokeMonoRoman_ch36st0[] =
{
 {42.8571f,119.048f},
 {42.8571f,-19.0476f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch36st1[] =
{
 {61.9047f,119.048f},
 {61.9047f,-19.0476f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch36st2[] =
{
 {85.7143f,85.7143f},
 {76.1905f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f},
 {28.5714f,95.2381f},
 {19.0476f,85.7143f},
 {19.0476f,76.1905f},
 {23.8095f,66.6667f},
 {28.5714f,61.9048f},
 {38.0952f,57.1429f},
 {66.6666f,47.619f},
 {76.1905f,42.8571f},
 {80.9524f,38.0952f},
 {85.7143f,28.5714f},
 {85.7143f,14.2857f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {19.0476f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch36st[] =
{
 {2,StrokeMonoRoman_ch36st0},
 {2,StrokeMonoRoman_ch36st1},
 {20,StrokeMonoRoman_ch36st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch36 = {104.762f,3,StrokeMonoRoman_ch36st};

/* char: 0x25 */

static const SFG_StrokeVertex StrokeMonoRoman_ch37st0[] =
{
 {95.2381f,100.0f},
 {9.5238f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch37st1[] =
{
 {33.3333f,100.0f},
 {42.8571f,90.4762f},
 {42.8571f,80.9524f},
 {38.0952f,71.4286f},
 {28.5714f,66.6667f},
 {19.0476f,66.6667f},
 {9.5238f,76.1905f},
 {9.5238f,85.7143f},
 {14.2857f,95.2381f},
 {23.8095f,100.0f},
 {33.3333f,100.0f},
 {42.8571f,95.2381f},
 {57.1428f,90.4762f},
 {71.4286f,90.4762f},
 {85.7143f,95.2381f},
 {95.2381f,100.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch37st2[] =
{
 {76.1905f,33.3333f},
 {66.6667f,28.5714f},
 {61.9048f,19.0476f},
 {61.9048f,9.5238f},
 {71.4286f,0.0f},
 {80.9524f,0.0f},
 {90.4762f,4.7619f},
 {95.2381f,14.2857f},
 {95.2381f,23.8095f},
 {85.7143f,33.3333f},
 {76.1905f,33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch37st[] =
{
 {2,StrokeMonoRoman_ch37st0},
 {16,StrokeMonoRoman_ch37st1},
 {11,StrokeMonoRoman_ch37st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch37 = {104.762f,3,StrokeMonoRoman_ch37st};

/* char: 0x26 */

static const SFG_StrokeVertex StrokeMonoRoman_ch38st0[] =
{
 {100.0f,57.1429f},
 {100.0f,61.9048f},
 {95.2381f,66.6667f},
 {90.4762f,66.6667f},
 {85.7143f,61.9048f},
 {80.9524f,52.381f},
 {71.4286f,28.5714f},
 {61.9048f,14.2857f},
 {52.3809f,4.7619f},
 {42.8571f,0.0f},
 {23.8095f,0.0f},
 {14.2857f,4.7619f},
 {9.5238f,9.5238f},
 {4.7619f,19.0476f},
 {4.7619f,28.5714f},
 {9.5238f,38.0952f},
 {14.2857f,42.8571f},
 {47.619f,61.9048f},
 {52.3809f,66.6667f},
 {57.1429f,76.1905f},
 {57.1429f,85.7143f},
 {52.3809f,95.2381f},
 {42.8571f,100.0f},
 {33.3333f,95.2381f},
 {28.5714f,85.7143f},
 {28.5714f,76.1905f},
 {33.3333f,61.9048f},
 {42.8571f,47.619f},
 {66.6667f,14.2857f},
 {76.1905f,4.7619f},
 {85.7143f,0.0f},
 {95.2381f,0.0f},
 {100.0f,4.7619f},
 {100.0f,9.5238f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch38st[] =
{
 {34,StrokeMonoRoman_ch38st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch38 = {104.762f,1,StrokeMonoRoman_ch38st};

/* char: 0x27 */

static const SFG_StrokeVertex StrokeMonoRoman_ch39st0[] =
{
 {52.381f,100.0f},
 {52.381f,66.6667f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch39st[] =
{
 {2,StrokeMonoRoman_ch39st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch39 = {104.762f,1,StrokeMonoRoman_ch39st};

/* char: 0x28 */

static const SFG_StrokeVertex StrokeMonoRoman_ch40st0[] =
{
 {69.0476f,119.048f},
 {59.5238f,109.524f},
 {50.0f,95.2381f},
 {40.4762f,76.1905f},
 {35.7143f,52.381f},
 {35.7143f,33.3333f},
 {40.4762f,9.5238f},
 {50.0f,-9.5238f},
 {59.5238f,-23.8095f},
 {69.0476f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch40st[] =
{
 {10,StrokeMonoRoman_ch40st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch40 = {104.762f,1,StrokeMonoRoman_ch40st};

/* char: 0x29 */

static const SFG_StrokeVertex StrokeMonoRoman_ch41st0[] =
{
 {35.7143f,119.048f},
 {45.2381f,109.524f},
 {54.7619f,95.2381f},
 {64.2857f,76.1905f},
 {69.0476f,52.381f},
 {69.0476f,33.3333f},
 {64.2857f,9.5238f},
 {54.7619f,-9.5238f},
 {45.2381f,-23.8095f},
 {35.7143f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch41st[] =
{
 {10,StrokeMonoRoman_ch41st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch41 = {104.762f,1,StrokeMonoRoman_ch41st};

/* char: 0x2a */

static const SFG_StrokeVertex StrokeMonoRoman_ch42st0[] =
{
 {52.381f,71.4286f},
 {52.381f,14.2857f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch42st1[] =
{
 {28.5715f,57.1429f},
 {76.1905f,28.5714f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch42st2[] =
{
 {76.1905f,57.1429f},
 {28.5715f,28.5714f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch42st[] =
{
 {2,StrokeMonoRoman_ch42st0},
 {2,StrokeMonoRoman_ch42st1},
 {2,StrokeMonoRoman_ch42st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch42 = {104.762f,3,StrokeMonoRoman_ch42st};

/* char: 0x2b */

static const SFG_StrokeVertex StrokeMonoRoman_ch43st0[] =
{
 {52.3809f,85.7143f},
 {52.3809f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch43st1[] =
{
 {9.5238f,42.8571f},
 {95.2381f,42.8571f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch43st[] =
{
 {2,StrokeMonoRoman_ch43st0},
 {2,StrokeMonoRoman_ch43st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch43 = {104.762f,2,StrokeMonoRoman_ch43st};

/* char: 0x2c */

static const SFG_StrokeVertex StrokeMonoRoman_ch44st0[] =
{
 {57.1429f,4.7619f},
 {52.381f,0.0f},
 {47.6191f,4.7619f},
 {52.381f,9.5238f},
 {57.1429f,4.7619f},
 {57.1429f,-4.7619f},
 {52.381f,-14.2857f},
 {47.6191f,-19.0476f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch44st[] =
{
 {8,StrokeMonoRoman_ch44st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch44 = {104.762f,1,StrokeMonoRoman_ch44st};

/* char: 0x2d */

static const SFG_StrokeVertex StrokeMonoRoman_ch45st0[] =
{
 {9.5238f,42.8571f},
 {95.2381f,42.8571f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch45st[] =
{
 {2,StrokeMonoRoman_ch45st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch45 = {104.762f,1,StrokeMonoRoman_ch45st};

/* char: 0x2e */

static const SFG_StrokeVertex StrokeMonoRoman_ch46st0[] =
{
 {52.381f,9.5238f},
 {47.6191f,4.7619f},
 {52.381f,0.0f},
 {57.1429f,4.7619f},
 {52.381f,9.5238f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch46st[] =
{
 {5,StrokeMonoRoman_ch46st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch46 = {104.762f,1,StrokeMonoRoman_ch46st};

/* char: 0x2f */

static const SFG_StrokeVertex StrokeMonoRoman_ch47st0[] =
{
 {19.0476f,-14.2857f},
 {85.7143f,100.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch47st[] =
{
 {2,StrokeMonoRoman_ch47st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch47 = {104.762f,1,StrokeMonoRoman_ch47st};

/* char: 0x30 */

static const SFG_StrokeVertex StrokeMonoRoman_ch48st0[] =
{
 {47.619f,100.0f},
 {33.3333f,95.2381f},
 {23.8095f,80.9524f},
 {19.0476f,57.1429f},
 {19.0476f,42.8571f},
 {23.8095f,19.0476f},
 {33.3333f,4.7619f},
 {47.619f,0.0f},
 {57.1428f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,19.0476f},
 {85.7143f,42.8571f},
 {85.7143f,57.1429f},
 {80.9524f,80.9524f},
 {71.4286f,95.2381f},
 {57.1428f,100.0f},
 {47.619f,100.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch48st[] =
{
 {17,StrokeMonoRoman_ch48st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch48 = {104.762f,1,StrokeMonoRoman_ch48st};

/* char: 0x31 */

static const SFG_StrokeVertex StrokeMonoRoman_ch49st0[] =
{
 {40.4762f,80.9524f},
 {50.0f,85.7143f},
 {64.2857f,100.0f},
 {64.2857f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch49st[] =
{
 {4,StrokeMonoRoman_ch49st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch49 = {104.762f,1,StrokeMonoRoman_ch49st};

/* char: 0x32 */

static const SFG_StrokeVertex StrokeMonoRoman_ch50st0[] =
{
 {23.8095f,76.1905f},
 {23.8095f,80.9524f},
 {28.5714f,90.4762f},
 {33.3333f,95.2381f},
 {42.8571f,100.0f},
 {61.9047f,100.0f},
 {71.4286f,95.2381f},
 {76.1905f,90.4762f},
 {80.9524f,80.9524f},
 {80.9524f,71.4286f},
 {76.1905f,61.9048f},
 {66.6666f,47.619f},
 {19.0476f,0.0f},
 {85.7143f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch50st[] =
{
 {14,StrokeMonoRoman_ch50st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch50 = {104.762f,1,StrokeMonoRoman_ch50st};

/* char: 0x33 */

static const SFG_StrokeVertex StrokeMonoRoman_ch51st0[] =
{
 {28.5714f,100.0f},
 {80.9524f,100.0f},
 {52.3809f,61.9048f},
 {66.6666f,61.9048f},
 {76.1905f,57.1429f},
 {80.9524f,52.381f},
 {85.7143f,38.0952f},
 {85.7143f,28.5714f},
 {80.9524f,14.2857f},
 {71.4286f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {23.8095f,9.5238f},
 {19.0476f,19.0476f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch51st[] =
{
 {15,StrokeMonoRoman_ch51st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch51 = {104.762f,1,StrokeMonoRoman_ch51st};

/* char: 0x34 */

static const SFG_StrokeVertex StrokeMonoRoman_ch52st0[] =
{
 {64.2857f,100.0f},
 {16.6667f,33.3333f},
 {88.0952f,33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch52st1[] =
{
 {64.2857f,100.0f},
 {64.2857f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch52st[] =
{
 {3,StrokeMonoRoman_ch52st0},
 {2,StrokeMonoRoman_ch52st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch52 = {104.762f,2,StrokeMonoRoman_ch52st};

/* char: 0x35 */

static const SFG_StrokeVertex StrokeMonoRoman_ch53st0[] =
{
 {76.1905f,100.0f},
 {28.5714f,100.0f},
 {23.8095f,57.1429f},
 {28.5714f,61.9048f},
 {42.8571f,66.6667f},
 {57.1428f,66.6667f},
 {71.4286f,61.9048f},
 {80.9524f,52.381f},
 {85.7143f,38.0952f},
 {85.7143f,28.5714f},
 {80.9524f,14.2857f},
 {71.4286f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {23.8095f,9.5238f},
 {19.0476f,19.0476f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch53st[] =
{
 {17,StrokeMonoRoman_ch53st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch53 = {104.762f,1,StrokeMonoRoman_ch53st};

/* char: 0x36 */

static const SFG_StrokeVertex StrokeMonoRoman_ch54st0[] =
{
 {78.5714f,85.7143f},
 {73.8096f,95.2381f},
 {59.5238f,100.0f},
 {50.0f,100.0f},
 {35.7143f,95.2381f},
 {26.1905f,80.9524f},
 {21.4286f,57.1429f},
 {21.4286f,33.3333f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {50.0f,0.0f},
 {54.7619f,0.0f},
 {69.0476f,4.7619f},
 {78.5714f,14.2857f},
 {83.3334f,28.5714f},
 {83.3334f,33.3333f},
 {78.5714f,47.619f},
 {69.0476f,57.1429f},
 {54.7619f,61.9048f},
 {50.0f,61.9048f},
 {35.7143f,57.1429f},
 {26.1905f,47.619f},
 {21.4286f,33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch54st[] =
{
 {23,StrokeMonoRoman_ch54st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch54 = {104.762f,1,StrokeMonoRoman_ch54st};

/* char: 0x37 */

static const SFG_StrokeVertex StrokeMonoRoman_ch55st0[] =
{
 {85.7143f,100.0f},
 {38.0952f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch55st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,100.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch55st[] =
{
 {2,StrokeMonoRoman_ch55st0},
 {2,StrokeMonoRoman_ch55st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch55 = {104.762f,2,StrokeMonoRoman_ch55st};

/* char: 0x38 */

static const SFG_StrokeVertex StrokeMonoRoman_ch56st0[] =
{
 {42.8571f,100.0f},
 {28.5714f,95.2381f},
 {23.8095f,85.7143f},
 {23.8095f,76.1905f},
 {28.5714f,66.6667f},
 {38.0952f,61.9048f},
 {57.1428f,57.1429f},
 {71.4286f,52.381f},
 {80.9524f,42.8571f},
 {85.7143f,33.3333f},
 {85.7143f,19.0476f},
 {80.9524f,9.5238f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {23.8095f,9.5238f},
 {19.0476f,19.0476f},
 {19.0476f,33.3333f},
 {23.8095f,42.8571f},
 {33.3333f,52.381f},
 {47.619f,57.1429f},
 {66.6666f,61.9048f},
 {76.1905f,66.6667f},
 {80.9524f,76.1905f},
 {80.9524f,85.7143f},
 {76.1905f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch56st[] =
{
 {29,StrokeMonoRoman_ch56st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch56 = {104.762f,1,StrokeMonoRoman_ch56st};

/* char: 0x39 */

static const SFG_StrokeVertex StrokeMonoRoman_ch57st0[] =
{
 {83.3334f,66.6667f},
 {78.5714f,52.381f},
 {69.0476f,42.8571f},
 {54.7619f,38.0952f},
 {50.0f,38.0952f},
 {35.7143f,42.8571f},
 {26.1905f,52.381f},
 {21.4286f,66.6667f},
 {21.4286f,71.4286f},
 {26.1905f,85.7143f},
 {35.7143f,95.2381f},
 {50.0f,100.0f},
 {54.7619f,100.0f},
 {69.0476f,95.2381f},
 {78.5714f,85.7143f},
 {83.3334f,66.6667f},
 {83.3334f,42.8571f},
 {78.5714f,19.0476f},
 {69.0476f,4.7619f},
 {54.7619f,0.0f},
 {45.2381f,0.0f},
 {30.9524f,4.7619f},
 {26.1905f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch57st[] =
{
 {23,StrokeMonoRoman_ch57st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch57 = {104.762f,1,StrokeMonoRoman_ch57st};

/* char: 0x3a */

static const SFG_StrokeVertex StrokeMonoRoman_ch58st0[] =
{
 {52.381f,66.6667f},
 {47.6191f,61.9048f},
 {52.381f,57.1429f},
 {57.1429f,61.9048f},
 {52.381f,66.6667f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch58st1[] =
{
 {52.381f,9.5238f},
 {47.6191f,4.7619f},
 {52.381f,0.0f},
 {57.1429f,4.7619f},
 {52.381f,9.5238f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch58st[] =
{
 {5,StrokeMonoRoman_ch58st0},
 {5,StrokeMonoRoman_ch58st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch58 = {104.762f,2,StrokeMonoRoman_ch58st};

/* char: 0x3b */

static const SFG_StrokeVertex StrokeMonoRoman_ch59st0[] =
{
 {52.381f,66.6667f},
 {47.6191f,61.9048f},
 {52.381f,57.1429f},
 {57.1429f,61.9048f},
 {52.381f,66.6667f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch59st1[] =
{
 {57.1429f,4.7619f},
 {52.381f,0.0f},
 {47.6191f,4.7619f},
 {52.381f,9.5238f},
 {57.1429f,4.7619f},
 {57.1429f,-4.7619f},
 {52.381f,-14.2857f},
 {47.6191f,-19.0476f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch59st[] =
{
 {5,StrokeMonoRoman_ch59st0},
 {8,StrokeMonoRoman_ch59st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch59 = {104.762f,2,StrokeMonoRoman_ch59st};

/* char: 0x3c */

static const SFG_StrokeVertex StrokeMonoRoman_ch60st0[] =
{
 {90.4762f,85.7143f},
 {14.2857f,42.8571f},
 {90.4762f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch60st[] =
{
 {3,StrokeMonoRoman_ch60st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch60 = {104.762f,1,StrokeMonoRoman_ch60st};

/* char: 0x3d */

static const SFG_StrokeVertex StrokeMonoRoman_ch61st0[] =
{
 {9.5238f,57.1429f},
 {95.2381f,57.1429f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch61st1[] =
{
 {9.5238f,28.5714f},
 {95.2381f,28.5714f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch61st[] =
{
 {2,StrokeMonoRoman_ch61st0},
 {2,StrokeMonoRoman_ch61st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch61 = {104.762f,2,StrokeMonoRoman_ch61st};

/* char: 0x3e */

static const SFG_StrokeVertex StrokeMonoRoman_ch62st0[] =
{
 {14.2857f,85.7143f},
 {90.4762f,42.8571f},
 {14.2857f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch62st[] =
{
 {3,StrokeMonoRoman_ch62st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch62 = {104.762f,1,StrokeMonoRoman_ch62st};

/* char: 0x3f */

static const SFG_StrokeVertex StrokeMonoRoman_ch63st0[] =
{
 {23.8095f,76.1905f},
 {23.8095f,80.9524f},
 {28.5714f,90.4762f},
 {33.3333f,95.2381f},
 {42.8571f,100.0f},
 {61.9047f,100.0f},
 {71.4285f,95.2381f},
 {76.1905f,90.4762f},
 {80.9524f,80.9524f},
 {80.9524f,71.4286f},
 {76.1905f,61.9048f},
 {71.4285f,57.1429f},
 {52.3809f,47.619f},
 {52.3809f,33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch63st1[] =
{
 {52.3809f,9.5238f},
 {47.619f,4.7619f},
 {52.3809f,0.0f},
 {57.1428f,4.7619f},
 {52.3809f,9.5238f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch63st[] =
{
 {14,StrokeMonoRoman_ch63st0},
 {5,StrokeMonoRoman_ch63st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch63 = {104.762f,2,StrokeMonoRoman_ch63st};

/* char: 0x40 */

static const SFG_StrokeVertex StrokeMonoRoman_ch64st0[] =
{
 {64.2857f,52.381f},
 {54.7619f,57.1429f},
 {45.2381f,57.1429f},
 {40.4762f,47.619f},
 {40.4762f,42.8571f},
 {45.2381f,33.3333f},
 {54.7619f,33.3333f},
 {64.2857f,38.0952f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch64st1[] =
{
 {64.2857f,57.1429f},
 {64.2857f,38.0952f},
 {69.0476f,33.3333f},
 {78.5714f,33.3333f},
 {83.3334f,42.8571f},
 {83.3334f,47.619f},
 {78.5714f,61.9048f},
 {69.0476f,71.4286f},
 {54.7619f,76.1905f},
 {50.0f,76.1905f},
 {35.7143f,71.4286f},
 {26.1905f,61.9048f},
 {21.4286f,47.619f},
 {21.4286f,42.8571f},
 {26.1905f,28.5714f},
 {35.7143f,19.0476f},
 {50.0f,14.2857f},
 {54.7619f,14.2857f},
 {69.0476f,19.0476f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch64st[] =
{
 {8,StrokeMonoRoman_ch64st0},
 {19,StrokeMonoRoman_ch64st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch64 = {104.762f,2,StrokeMonoRoman_ch64st};

/* char: 0x41 */

static const SFG_StrokeVertex StrokeMonoRoman_ch65st0[] =
{
 {52.3809f,100.0f},
 {14.2857f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch65st1[] =
{
 {52.3809f,100.0f},
 {90.4762f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch65st2[] =
{
 {28.5714f,33.3333f},
 {76.1905f,33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch65st[] =
{
 {2,StrokeMonoRoman_ch65st0},
 {2,StrokeMonoRoman_ch65st1},
 {2,StrokeMonoRoman_ch65st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch65 = {104.762f,3,StrokeMonoRoman_ch65st};

/* char: 0x42 */

static const SFG_StrokeVertex StrokeMonoRoman_ch66st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch66st1[] =
{
 {19.0476f,100.0f},
 {61.9047f,100.0f},
 {76.1905f,95.2381f},
 {80.9524f,90.4762f},
 {85.7143f,80.9524f},
 {85.7143f,71.4286f},
 {80.9524f,61.9048f},
 {76.1905f,57.1429f},
 {61.9047f,52.381f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch66st2[] =
{
 {19.0476f,52.381f},
 {61.9047f,52.381f},
 {76.1905f,47.619f},
 {80.9524f,42.8571f},
 {85.7143f,33.3333f},
 {85.7143f,19.0476f},
 {80.9524f,9.5238f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch66st[] =
{
 {2,StrokeMonoRoman_ch66st0},
 {9,StrokeMonoRoman_ch66st1},
 {10,StrokeMonoRoman_ch66st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch66 = {104.762f,3,StrokeMonoRoman_ch66st};

/* char: 0x43 */

static const SFG_StrokeVertex StrokeMonoRoman_ch67st0[] =
{
 {88.0952f,76.1905f},
 {83.3334f,85.7143f},
 {73.8096f,95.2381f},
 {64.2857f,100.0f},
 {45.2381f,100.0f},
 {35.7143f,95.2381f},
 {26.1905f,85.7143f},
 {21.4286f,76.1905f},
 {16.6667f,61.9048f},
 {16.6667f,38.0952f},
 {21.4286f,23.8095f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {45.2381f,0.0f},
 {64.2857f,0.0f},
 {73.8096f,4.7619f},
 {83.3334f,14.2857f},
 {88.0952f,23.8095f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch67st[] =
{
 {18,StrokeMonoRoman_ch67st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch67 = {104.762f,1,StrokeMonoRoman_ch67st};

/* char: 0x44 */

static const SFG_StrokeVertex StrokeMonoRoman_ch68st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch68st1[] =
{
 {19.0476f,100.0f},
 {52.3809f,100.0f},
 {66.6666f,95.2381f},
 {76.1905f,85.7143f},
 {80.9524f,76.1905f},
 {85.7143f,61.9048f},
 {85.7143f,38.0952f},
 {80.9524f,23.8095f},
 {76.1905f,14.2857f},
 {66.6666f,4.7619f},
 {52.3809f,0.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch68st[] =
{
 {2,StrokeMonoRoman_ch68st0},
 {12,StrokeMonoRoman_ch68st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch68 = {104.762f,2,StrokeMonoRoman_ch68st};

/* char: 0x45 */

static const SFG_StrokeVertex StrokeMonoRoman_ch69st0[] =
{
 {21.4286f,100.0f},
 {21.4286f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch69st1[] =
{
 {21.4286f,100.0f},
 {83.3334f,100.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch69st2[] =
{
 {21.4286f,52.381f},
 {59.5238f,52.381f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch69st3[] =
{
 {21.4286f,0.0f},
 {83.3334f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch69st[] =
{
 {2,StrokeMonoRoman_ch69st0},
 {2,StrokeMonoRoman_ch69st1},
 {2,StrokeMonoRoman_ch69st2},
 {2,StrokeMonoRoman_ch69st3}
};

static const SFG_StrokeChar StrokeMonoRoman_ch69 = {104.762f,4,StrokeMonoRoman_ch69st};

/* char: 0x46 */

static const SFG_StrokeVertex StrokeMonoRoman_ch70st0[] =
{
 {21.4286f,100.0f},
 {21.4286f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch70st1[] =
{
 {21.4286f,100.0f},
 {83.3334f,100.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch70st2[] =
{
 {21.4286f,52.381f},
 {59.5238f,52.381f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch70st[] =
{
 {2,StrokeMonoRoman_ch70st0},
 {2,StrokeMonoRoman_ch70st1},
 {2,StrokeMonoRoman_ch70st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch70 = {104.762f,3,StrokeMonoRoman_ch70st};

/* char: 0x47 */

static const SFG_StrokeVertex StrokeMonoRoman_ch71st0[] =
{
 {88.0952f,76.1905f},
 {83.3334f,85.7143f},
 {73.8096f,95.2381f},
 {64.2857f,100.0f},
 {45.2381f,100.0f},
 {35.7143f,95.2381f},
 {26.1905f,85.7143f},
 {21.4286f,76.1905f},
 {16.6667f,61.9048f},
 {16.6667f,38.0952f},
 {21.4286f,23.8095f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {45.2381f,0.0f},
 {64.2857f,0.0f},
 {73.8096f,4.7619f},
 {83.3334f,14.2857f},
 {88.0952f,23.8095f},
 {88.0952f,38.0952f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch71st1[] =
{
 {64.2857f,38.0952f},
 {88.0952f,38.0952f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch71st[] =
{
 {19,StrokeMonoRoman_ch71st0},
 {2,StrokeMonoRoman_ch71st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch71 = {104.762f,2,StrokeMonoRoman_ch71st};

/* char: 0x48 */

static const SFG_StrokeVertex StrokeMonoRoman_ch72st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch72st1[] =
{
 {85.7143f,100.0f},
 {85.7143f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch72st2[] =
{
 {19.0476f,52.381f},
 {85.7143f,52.381f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch72st[] =
{
 {2,StrokeMonoRoman_ch72st0},
 {2,StrokeMonoRoman_ch72st1},
 {2,StrokeMonoRoman_ch72st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch72 = {104.762f,3,StrokeMonoRoman_ch72st};

/* char: 0x49 */

static const SFG_StrokeVertex StrokeMonoRoman_ch73st0[] =
{
 {52.381f,100.0f},
 {52.381f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch73st[] =
{
 {2,StrokeMonoRoman_ch73st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch73 = {104.762f,1,StrokeMonoRoman_ch73st};

/* char: 0x4a */

static const SFG_StrokeVertex StrokeMonoRoman_ch74st0[] =
{
 {76.1905f,100.0f},
 {76.1905f,23.8095f},
 {71.4286f,9.5238f},
 {66.6667f,4.7619f},
 {57.1429f,0.0f},
 {47.6191f,0.0f},
 {38.0953f,4.7619f},
 {33.3334f,9.5238f},
 {28.5715f,23.8095f},
 {28.5715f,33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch74st[] =
{
 {10,StrokeMonoRoman_ch74st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch74 = {104.762f,1,StrokeMonoRoman_ch74st};

/* char: 0x4b */

static const SFG_StrokeVertex StrokeMonoRoman_ch75st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch75st1[] =
{
 {85.7143f,100.0f},
 {19.0476f,33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch75st2[] =
{
 {42.8571f,57.1429f},
 {85.7143f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch75st[] =
{
 {2,StrokeMonoRoman_ch75st0},
 {2,StrokeMonoRoman_ch75st1},
 {2,StrokeMonoRoman_ch75st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch75 = {104.762f,3,StrokeMonoRoman_ch75st};

/* char: 0x4c */

static const SFG_StrokeVertex StrokeMonoRoman_ch76st0[] =
{
 {23.8095f,100.0f},
 {23.8095f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch76st1[] =
{
 {23.8095f,0.0f},
 {80.9524f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch76st[] =
{
 {2,StrokeMonoRoman_ch76st0},
 {2,StrokeMonoRoman_ch76st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch76 = {104.762f,2,StrokeMonoRoman_ch76st};

/* char: 0x4d */

static const SFG_StrokeVertex StrokeMonoRoman_ch77st0[] =
{
 {14.2857f,100.0f},
 {14.2857f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch77st1[] =
{
 {14.2857f,100.0f},
 {52.3809f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch77st2[] =
{
 {90.4762f,100.0f},
 {52.3809f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch77st3[] =
{
 {90.4762f,100.0f},
 {90.4762f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch77st[] =
{
 {2,StrokeMonoRoman_ch77st0},
 {2,StrokeMonoRoman_ch77st1},
 {2,StrokeMonoRoman_ch77st2},
 {2,StrokeMonoRoman_ch77st3}
};

static const SFG_StrokeChar StrokeMonoRoman_ch77 = {104.762f,4,StrokeMonoRoman_ch77st};

/* char: 0x4e */

static const SFG_StrokeVertex StrokeMonoRoman_ch78st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch78st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch78st2[] =
{
 {85.7143f,100.0f},
 {85.7143f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch78st[] =
{
 {2,StrokeMonoRoman_ch78st0},
 {2,StrokeMonoRoman_ch78st1},
 {2,StrokeMonoRoman_ch78st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch78 = {104.762f,3,StrokeMonoRoman_ch78st};

/* char: 0x4f */

static const SFG_StrokeVertex StrokeMonoRoman_ch79st0[] =
{
 {42.8571f,100.0f},
 {33.3333f,95.2381f},
 {23.8095f,85.7143f},
 {19.0476f,76.1905f},
 {14.2857f,61.9048f},
 {14.2857f,38.0952f},
 {19.0476f,23.8095f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {42.8571f,0.0f},
 {61.9047f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,23.8095f},
 {90.4762f,38.0952f},
 {90.4762f,61.9048f},
 {85.7143f,76.1905f},
 {80.9524f,85.7143f},
 {71.4286f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch79st[] =
{
 {21,StrokeMonoRoman_ch79st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch79 = {104.762f,1,StrokeMonoRoman_ch79st};

/* char: 0x50 */

static const SFG_StrokeVertex StrokeMonoRoman_ch80st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch80st1[] =
{
 {19.0476f,100.0f},
 {61.9047f,100.0f},
 {76.1905f,95.2381f},
 {80.9524f,90.4762f},
 {85.7143f,80.9524f},
 {85.7143f,66.6667f},
 {80.9524f,57.1429f},
 {76.1905f,52.381f},
 {61.9047f,47.619f},
 {19.0476f,47.619f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch80st[] =
{
 {2,StrokeMonoRoman_ch80st0},
 {10,StrokeMonoRoman_ch80st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch80 = {104.762f,2,StrokeMonoRoman_ch80st};

/* char: 0x51 */

static const SFG_StrokeVertex StrokeMonoRoman_ch81st0[] =
{
 {42.8571f,100.0f},
 {33.3333f,95.2381f},
 {23.8095f,85.7143f},
 {19.0476f,76.1905f},
 {14.2857f,61.9048f},
 {14.2857f,38.0952f},
 {19.0476f,23.8095f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {42.8571f,0.0f},
 {61.9047f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,23.8095f},
 {90.4762f,38.0952f},
 {90.4762f,61.9048f},
 {85.7143f,76.1905f},
 {80.9524f,85.7143f},
 {71.4286f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch81st1[] =
{
 {57.1428f,19.0476f},
 {85.7143f,-9.5238f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch81st[] =
{
 {21,StrokeMonoRoman_ch81st0},
 {2,StrokeMonoRoman_ch81st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch81 = {104.762f,2,StrokeMonoRoman_ch81st};

/* char: 0x52 */

static const SFG_StrokeVertex StrokeMonoRoman_ch82st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch82st1[] =
{
 {19.0476f,100.0f},
 {61.9047f,100.0f},
 {76.1905f,95.2381f},
 {80.9524f,90.4762f},
 {85.7143f,80.9524f},
 {85.7143f,71.4286f},
 {80.9524f,61.9048f},
 {76.1905f,57.1429f},
 {61.9047f,52.381f},
 {19.0476f,52.381f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch82st2[] =
{
 {52.3809f,52.381f},
 {85.7143f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch82st[] =
{
 {2,StrokeMonoRoman_ch82st0},
 {10,StrokeMonoRoman_ch82st1},
 {2,StrokeMonoRoman_ch82st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch82 = {104.762f,3,StrokeMonoRoman_ch82st};

/* char: 0x53 */

static const SFG_StrokeVertex StrokeMonoRoman_ch83st0[] =
{
 {85.7143f,85.7143f},
 {76.1905f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f},
 {28.5714f,95.2381f},
 {19.0476f,85.7143f},
 {19.0476f,76.1905f},
 {23.8095f,66.6667f},
 {28.5714f,61.9048f},
 {38.0952f,57.1429f},
 {66.6666f,47.619f},
 {76.1905f,42.8571f},
 {80.9524f,38.0952f},
 {85.7143f,28.5714f},
 {85.7143f,14.2857f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {19.0476f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch83st[] =
{
 {20,StrokeMonoRoman_ch83st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch83 = {104.762f,1,StrokeMonoRoman_ch83st};

/* char: 0x54 */

static const SFG_StrokeVertex StrokeMonoRoman_ch84st0[] =
{
 {52.3809f,100.0f},
 {52.3809f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch84st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,100.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch84st[] =
{
 {2,StrokeMonoRoman_ch84st0},
 {2,StrokeMonoRoman_ch84st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch84 = {104.762f,2,StrokeMonoRoman_ch84st};

/* char: 0x55 */

static const SFG_StrokeVertex StrokeMonoRoman_ch85st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,28.5714f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {47.619f,0.0f},
 {57.1428f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,28.5714f},
 {85.7143f,100.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch85st[] =
{
 {10,StrokeMonoRoman_ch85st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch85 = {104.762f,1,StrokeMonoRoman_ch85st};

/* char: 0x56 */

static const SFG_StrokeVertex StrokeMonoRoman_ch86st0[] =
{
 {14.2857f,100.0f},
 {52.3809f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch86st1[] =
{
 {90.4762f,100.0f},
 {52.3809f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch86st[] =
{
 {2,StrokeMonoRoman_ch86st0},
 {2,StrokeMonoRoman_ch86st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch86 = {104.762f,2,StrokeMonoRoman_ch86st};

/* char: 0x57 */

static const SFG_StrokeVertex StrokeMonoRoman_ch87st0[] =
{
 {4.7619f,100.0f},
 {28.5714f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch87st1[] =
{
 {52.3809f,100.0f},
 {28.5714f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch87st2[] =
{
 {52.3809f,100.0f},
 {76.1905f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch87st3[] =
{
 {100.0f,100.0f},
 {76.1905f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch87st[] =
{
 {2,StrokeMonoRoman_ch87st0},
 {2,StrokeMonoRoman_ch87st1},
 {2,StrokeMonoRoman_ch87st2},
 {2,StrokeMonoRoman_ch87st3}
};

static const SFG_StrokeChar StrokeMonoRoman_ch87 = {104.762f,4,StrokeMonoRoman_ch87st};

/* char: 0x58 */

static const SFG_StrokeVertex StrokeMonoRoman_ch88st0[] =
{
 {19.0476f,100.0f},
 {85.7143f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch88st1[] =
{
 {85.7143f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch88st[] =
{
 {2,StrokeMonoRoman_ch88st0},
 {2,StrokeMonoRoman_ch88st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch88 = {104.762f,2,StrokeMonoRoman_ch88st};

/* char: 0x59 */

static const SFG_StrokeVertex StrokeMonoRoman_ch89st0[] =
{
 {14.2857f,100.0f},
 {52.3809f,52.381f},
 {52.3809f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch89st1[] =
{
 {90.4762f,100.0f},
 {52.3809f,52.381f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch89st[] =
{
 {3,StrokeMonoRoman_ch89st0},
 {2,StrokeMonoRoman_ch89st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch89 = {104.762f,2,StrokeMonoRoman_ch89st};

/* char: 0x5a */

static const SFG_StrokeVertex StrokeMonoRoman_ch90st0[] =
{
 {85.7143f,100.0f},
 {19.0476f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch90st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,100.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch90st2[] =
{
 {19.0476f,0.0f},
 {85.7143f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch90st[] =
{
 {2,StrokeMonoRoman_ch90st0},
 {2,StrokeMonoRoman_ch90st1},
 {2,StrokeMonoRoman_ch90st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch90 = {104.762f,3,StrokeMonoRoman_ch90st};

/* char: 0x5b */

static const SFG_StrokeVertex StrokeMonoRoman_ch91st0[] =
{
 {35.7143f,119.048f},
 {35.7143f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch91st1[] =
{
 {40.4762f,119.048f},
 {40.4762f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch91st2[] =
{
 {35.7143f,119.048f},
 {69.0476f,119.048f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch91st3[] =
{
 {35.7143f,-33.3333f},
 {69.0476f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch91st[] =
{
 {2,StrokeMonoRoman_ch91st0},
 {2,StrokeMonoRoman_ch91st1},
 {2,StrokeMonoRoman_ch91st2},
 {2,StrokeMonoRoman_ch91st3}
};

static const SFG_StrokeChar StrokeMonoRoman_ch91 = {104.762f,4,StrokeMonoRoman_ch91st};

/* char: 0x5c */

static const SFG_StrokeVertex StrokeMonoRoman_ch92st0[] =
{
 {19.0476f,100.0f},
 {85.7143f,-14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch92st[] =
{
 {2,StrokeMonoRoman_ch92st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch92 = {104.762f,1,StrokeMonoRoman_ch92st};

/* char: 0x5d */

static const SFG_StrokeVertex StrokeMonoRoman_ch93st0[] =
{
 {64.2857f,119.048f},
 {64.2857f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch93st1[] =
{
 {69.0476f,119.048f},
 {69.0476f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch93st2[] =
{
 {35.7143f,119.048f},
 {69.0476f,119.048f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch93st3[] =
{
 {35.7143f,-33.3333f},
 {69.0476f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch93st[] =
{
 {2,StrokeMonoRoman_ch93st0},
 {2,StrokeMonoRoman_ch93st1},
 {2,StrokeMonoRoman_ch93st2},
 {2,StrokeMonoRoman_ch93st3}
};

static const SFG_StrokeChar StrokeMonoRoman_ch93 = {104.762f,4,StrokeMonoRoman_ch93st};

/* char: 0x5e */

static const SFG_StrokeVertex StrokeMonoRoman_ch94st0[] =
{
 {52.3809f,109.524f},
 {14.2857f,42.8571f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch94st1[] =
{
 {52.3809f,109.524f},
 {90.4762f,42.8571f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch94st[] =
{
 {2,StrokeMonoRoman_ch94st0},
 {2,StrokeMonoRoman_ch94st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch94 = {104.762f,2,StrokeMonoRoman_ch94st};

/* char: 0x5f */

static const SFG_StrokeVertex StrokeMonoRoman_ch95st0[] =
{
 {0,-33.3333f},
 {104.762f,-33.3333f},
 {104.762f,-28.5714f},
 {0,-28.5714f},
 {0,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch95st[] =
{
 {5,StrokeMonoRoman_ch95st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch95 = {104.762f,1,StrokeMonoRoman_ch95st};

/* char: 0x60 */

static const SFG_StrokeVertex StrokeMonoRoman_ch96st0[] =
{
 {42.8572f,100.0f},
 {66.6667f,71.4286f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch96st1[] =
{
 {42.8572f,100.0f},
 {38.0953f,95.2381f},
 {66.6667f,71.4286f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch96st[] =
{
 {2,StrokeMonoRoman_ch96st0},
 {3,StrokeMonoRoman_ch96st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch96 = {104.762f,2,StrokeMonoRoman_ch96st};

/* char: 0x61 */

static const SFG_StrokeVertex StrokeMonoRoman_ch97st0[] =
{
 {80.9524f,66.6667f},
 {80.9524f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch97st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch97st[] =
{
 {2,StrokeMonoRoman_ch97st0},
 {14,StrokeMonoRoman_ch97st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch97 = {104.762f,2,StrokeMonoRoman_ch97st};

/* char: 0x62 */

static const SFG_StrokeVertex StrokeMonoRoman_ch98st0[] =
{
 {23.8095f,100.0f},
 {23.8095f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch98st1[] =
{
 {23.8095f,52.381f},
 {33.3333f,61.9048f},
 {42.8571f,66.6667f},
 {57.1428f,66.6667f},
 {66.6666f,61.9048f},
 {76.1905f,52.381f},
 {80.9524f,38.0952f},
 {80.9524f,28.5714f},
 {76.1905f,14.2857f},
 {66.6666f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {33.3333f,4.7619f},
 {23.8095f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch98st[] =
{
 {2,StrokeMonoRoman_ch98st0},
 {14,StrokeMonoRoman_ch98st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch98 = {104.762f,2,StrokeMonoRoman_ch98st};

/* char: 0x63 */

static const SFG_StrokeVertex StrokeMonoRoman_ch99st0[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch99st[] =
{
 {14,StrokeMonoRoman_ch99st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch99 = {104.762f,1,StrokeMonoRoman_ch99st};

/* char: 0x64 */

static const SFG_StrokeVertex StrokeMonoRoman_ch100st0[] =
{
 {80.9524f,100.0f},
 {80.9524f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch100st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch100st[] =
{
 {2,StrokeMonoRoman_ch100st0},
 {14,StrokeMonoRoman_ch100st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch100 = {104.762f,2,StrokeMonoRoman_ch100st};

/* char: 0x65 */

static const SFG_StrokeVertex StrokeMonoRoman_ch101st0[] =
{
 {23.8095f,38.0952f},
 {80.9524f,38.0952f},
 {80.9524f,47.619f},
 {76.1905f,57.1429f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch101st[] =
{
 {17,StrokeMonoRoman_ch101st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch101 = {104.762f,1,StrokeMonoRoman_ch101st};

/* char: 0x66 */

static const SFG_StrokeVertex StrokeMonoRoman_ch102st0[] =
{
 {71.4286f,100.0f},
 {61.9048f,100.0f},
 {52.381f,95.2381f},
 {47.6191f,80.9524f},
 {47.6191f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch102st1[] =
{
 {33.3334f,66.6667f},
 {66.6667f,66.6667f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch102st[] =
{
 {5,StrokeMonoRoman_ch102st0},
 {2,StrokeMonoRoman_ch102st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch102 = {104.762f,2,StrokeMonoRoman_ch102st};

/* char: 0x67 */

static const SFG_StrokeVertex StrokeMonoRoman_ch103st0[] =
{
 {80.9524f,66.6667f},
 {80.9524f,-9.5238f},
 {76.1905f,-23.8095f},
 {71.4285f,-28.5714f},
 {61.9047f,-33.3333f},
 {47.619f,-33.3333f},
 {38.0952f,-28.5714f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch103st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch103st[] =
{
 {7,StrokeMonoRoman_ch103st0},
 {14,StrokeMonoRoman_ch103st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch103 = {104.762f,2,StrokeMonoRoman_ch103st};

/* char: 0x68 */

static const SFG_StrokeVertex StrokeMonoRoman_ch104st0[] =
{
 {26.1905f,100.0f},
 {26.1905f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch104st1[] =
{
 {26.1905f,47.619f},
 {40.4762f,61.9048f},
 {50.0f,66.6667f},
 {64.2857f,66.6667f},
 {73.8095f,61.9048f},
 {78.5715f,47.619f},
 {78.5715f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch104st[] =
{
 {2,StrokeMonoRoman_ch104st0},
 {7,StrokeMonoRoman_ch104st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch104 = {104.762f,2,StrokeMonoRoman_ch104st};

/* char: 0x69 */

static const SFG_StrokeVertex StrokeMonoRoman_ch105st0[] =
{
 {47.6191f,100.0f},
 {52.381f,95.2381f},
 {57.1429f,100.0f},
 {52.381f,104.762f},
 {47.6191f,100.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch105st1[] =
{
 {52.381f,66.6667f},
 {52.381f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch105st[] =
{
 {5,StrokeMonoRoman_ch105st0},
 {2,StrokeMonoRoman_ch105st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch105 = {104.762f,2,StrokeMonoRoman_ch105st};

/* char: 0x6a */

static const SFG_StrokeVertex StrokeMonoRoman_ch106st0[] =
{
 {57.1429f,100.0f},
 {61.9048f,95.2381f},
 {66.6667f,100.0f},
 {61.9048f,104.762f},
 {57.1429f,100.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch106st1[] =
{
 {61.9048f,66.6667f},
 {61.9048f,-14.2857f},
 {57.1429f,-28.5714f},
 {47.6191f,-33.3333f},
 {38.0953f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch106st[] =
{
 {5,StrokeMonoRoman_ch106st0},
 {5,StrokeMonoRoman_ch106st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch106 = {104.762f,2,StrokeMonoRoman_ch106st};

/* char: 0x6b */

static const SFG_StrokeVertex StrokeMonoRoman_ch107st0[] =
{
 {26.1905f,100.0f},
 {26.1905f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch107st1[] =
{
 {73.8095f,66.6667f},
 {26.1905f,19.0476f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch107st2[] =
{
 {45.2381f,38.0952f},
 {78.5715f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch107st[] =
{
 {2,StrokeMonoRoman_ch107st0},
 {2,StrokeMonoRoman_ch107st1},
 {2,StrokeMonoRoman_ch107st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch107 = {104.762f,3,StrokeMonoRoman_ch107st};

/* char: 0x6c */

static const SFG_StrokeVertex StrokeMonoRoman_ch108st0[] =
{
 {52.381f,100.0f},
 {52.381f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch108st[] =
{
 {2,StrokeMonoRoman_ch108st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch108 = {104.762f,1,StrokeMonoRoman_ch108st};

/* char: 0x6d */

static const SFG_StrokeVertex StrokeMonoRoman_ch109st0[] =
{
 {0,66.6667f},
 {0,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch109st1[] =
{
 {0,47.619f},
 {14.2857f,61.9048f},
 {23.8095f,66.6667f},
 {38.0952f,66.6667f},
 {47.619f,61.9048f},
 {52.381f,47.619f},
 {52.381f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch109st2[] =
{
 {52.381f,47.619f},
 {66.6667f,61.9048f},
 {76.1905f,66.6667f},
 {90.4762f,66.6667f},
 {100.0f,61.9048f},
 {104.762f,47.619f},
 {104.762f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch109st[] =
{
 {2,StrokeMonoRoman_ch109st0},
 {7,StrokeMonoRoman_ch109st1},
 {7,StrokeMonoRoman_ch109st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch109 = {104.762f,3,StrokeMonoRoman_ch109st};

/* char: 0x6e */

static const SFG_StrokeVertex StrokeMonoRoman_ch110st0[] =
{
 {26.1905f,66.6667f},
 {26.1905f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch110st1[] =
{
 {26.1905f,47.619f},
 {40.4762f,61.9048f},
 {50.0f,66.6667f},
 {64.2857f,66.6667f},
 {73.8095f,61.9048f},
 {78.5715f,47.619f},
 {78.5715f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch110st[] =
{
 {2,StrokeMonoRoman_ch110st0},
 {7,StrokeMonoRoman_ch110st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch110 = {104.762f,2,StrokeMonoRoman_ch110st};

/* char: 0x6f */

static const SFG_StrokeVertex StrokeMonoRoman_ch111st0[] =
{
 {45.2381f,66.6667f},
 {35.7143f,61.9048f},
 {26.1905f,52.381f},
 {21.4286f,38.0952f},
 {21.4286f,28.5714f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {45.2381f,0.0f},
 {59.5238f,0.0f},
 {69.0476f,4.7619f},
 {78.5714f,14.2857f},
 {83.3334f,28.5714f},
 {83.3334f,38.0952f},
 {78.5714f,52.381f},
 {69.0476f,61.9048f},
 {59.5238f,66.6667f},
 {45.2381f,66.6667f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch111st[] =
{
 {17,StrokeMonoRoman_ch111st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch111 = {104.762f,1,StrokeMonoRoman_ch111st};

/* char: 0x70 */

static const SFG_StrokeVertex StrokeMonoRoman_ch112st0[] =
{
 {23.8095f,66.6667f},
 {23.8095f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch112st1[] =
{
 {23.8095f,52.381f},
 {33.3333f,61.9048f},
 {42.8571f,66.6667f},
 {57.1428f,66.6667f},
 {66.6666f,61.9048f},
 {76.1905f,52.381f},
 {80.9524f,38.0952f},
 {80.9524f,28.5714f},
 {76.1905f,14.2857f},
 {66.6666f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {33.3333f,4.7619f},
 {23.8095f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch112st[] =
{
 {2,StrokeMonoRoman_ch112st0},
 {14,StrokeMonoRoman_ch112st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch112 = {104.762f,2,StrokeMonoRoman_ch112st};

/* char: 0x71 */

static const SFG_StrokeVertex StrokeMonoRoman_ch113st0[] =
{
 {80.9524f,66.6667f},
 {80.9524f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch113st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch113st[] =
{
 {2,StrokeMonoRoman_ch113st0},
 {14,StrokeMonoRoman_ch113st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch113 = {104.762f,2,StrokeMonoRoman_ch113st};

/* char: 0x72 */

static const SFG_StrokeVertex StrokeMonoRoman_ch114st0[] =
{
 {33.3334f,66.6667f},
 {33.3334f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch114st1[] =
{
 {33.3334f,38.0952f},
 {38.0953f,52.381f},
 {47.6191f,61.9048f},
 {57.1429f,66.6667f},
 {71.4286f,66.6667f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch114st[] =
{
 {2,StrokeMonoRoman_ch114st0},
 {5,StrokeMonoRoman_ch114st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch114 = {104.762f,2,StrokeMonoRoman_ch114st};

/* char: 0x73 */

static const SFG_StrokeVertex StrokeMonoRoman_ch115st0[] =
{
 {78.5715f,52.381f},
 {73.8095f,61.9048f},
 {59.5238f,66.6667f},
 {45.2381f,66.6667f},
 {30.9524f,61.9048f},
 {26.1905f,52.381f},
 {30.9524f,42.8571f},
 {40.4762f,38.0952f},
 {64.2857f,33.3333f},
 {73.8095f,28.5714f},
 {78.5715f,19.0476f},
 {78.5715f,14.2857f},
 {73.8095f,4.7619f},
 {59.5238f,0.0f},
 {45.2381f,0.0f},
 {30.9524f,4.7619f},
 {26.1905f,14.2857f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch115st[] =
{
 {17,StrokeMonoRoman_ch115st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch115 = {104.762f,1,StrokeMonoRoman_ch115st};

/* char: 0x74 */

static const SFG_StrokeVertex StrokeMonoRoman_ch116st0[] =
{
 {47.6191f,100.0f},
 {47.6191f,19.0476f},
 {52.381f,4.7619f},
 {61.9048f,0.0f},
 {71.4286f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch116st1[] =
{
 {33.3334f,66.6667f},
 {66.6667f,66.6667f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch116st[] =
{
 {5,StrokeMonoRoman_ch116st0},
 {2,StrokeMonoRoman_ch116st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch116 = {104.762f,2,StrokeMonoRoman_ch116st};

/* char: 0x75 */

static const SFG_StrokeVertex StrokeMonoRoman_ch117st0[] =
{
 {26.1905f,66.6667f},
 {26.1905f,19.0476f},
 {30.9524f,4.7619f},
 {40.4762f,0.0f},
 {54.7619f,0.0f},
 {64.2857f,4.7619f},
 {78.5715f,19.0476f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch117st1[] =
{
 {78.5715f,66.6667f},
 {78.5715f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch117st[] =
{
 {7,StrokeMonoRoman_ch117st0},
 {2,StrokeMonoRoman_ch117st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch117 = {104.762f,2,StrokeMonoRoman_ch117st};

/* char: 0x76 */

static const SFG_StrokeVertex StrokeMonoRoman_ch118st0[] =
{
 {23.8095f,66.6667f},
 {52.3809f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch118st1[] =
{
 {80.9524f,66.6667f},
 {52.3809f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch118st[] =
{
 {2,StrokeMonoRoman_ch118st0},
 {2,StrokeMonoRoman_ch118st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch118 = {104.762f,2,StrokeMonoRoman_ch118st};

/* char: 0x77 */

static const SFG_StrokeVertex StrokeMonoRoman_ch119st0[] =
{
 {14.2857f,66.6667f},
 {33.3333f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch119st1[] =
{
 {52.3809f,66.6667f},
 {33.3333f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch119st2[] =
{
 {52.3809f,66.6667f},
 {71.4286f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch119st3[] =
{
 {90.4762f,66.6667f},
 {71.4286f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch119st[] =
{
 {2,StrokeMonoRoman_ch119st0},
 {2,StrokeMonoRoman_ch119st1},
 {2,StrokeMonoRoman_ch119st2},
 {2,StrokeMonoRoman_ch119st3}
};

static const SFG_StrokeChar StrokeMonoRoman_ch119 = {104.762f,4,StrokeMonoRoman_ch119st};

/* char: 0x78 */

static const SFG_StrokeVertex StrokeMonoRoman_ch120st0[] =
{
 {26.1905f,66.6667f},
 {78.5715f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch120st1[] =
{
 {78.5715f,66.6667f},
 {26.1905f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch120st[] =
{
 {2,StrokeMonoRoman_ch120st0},
 {2,StrokeMonoRoman_ch120st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch120 = {104.762f,2,StrokeMonoRoman_ch120st};

/* char: 0x79 */

static const SFG_StrokeVertex StrokeMonoRoman_ch121st0[] =
{
 {26.1905f,66.6667f},
 {54.7619f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch121st1[] =
{
 {83.3334f,66.6667f},
 {54.7619f,0.0f},
 {45.2381f,-19.0476f},
 {35.7143f,-28.5714f},
 {26.1905f,-33.3333f},
 {21.4286f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch121st[] =
{
 {2,StrokeMonoRoman_ch121st0},
 {6,StrokeMonoRoman_ch121st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch121 = {104.762f,2,StrokeMonoRoman_ch121st};

/* char: 0x7a */

static const SFG_StrokeVertex StrokeMonoRoman_ch122st0[] =
{
 {78.5715f,66.6667f},
 {26.1905f,0.0f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch122st1[] =
{
 {26.1905f,66.6667f},
 {78.5715f,66.6667f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch122st2[] =
{
 {26.1905f,0.0f},
 {78.5715f,0.0f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch122st[] =
{
 {2,StrokeMonoRoman_ch122st0},
 {2,StrokeMonoRoman_ch122st1},
 {2,StrokeMonoRoman_ch122st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch122 = {104.762f,3,StrokeMonoRoman_ch122st};

/* char: 0x7b */

static const SFG_StrokeVertex StrokeMonoRoman_ch123st0[] =
{
 {64.2857f,119.048f},
 {54.7619f,114.286f},
 {50.0f,109.524f},
 {45.2381f,100.0f},
 {45.2381f,90.4762f},
 {50.0f,80.9524f},
 {54.7619f,76.1905f},
 {59.5238f,66.6667f},
 {59.5238f,57.1429f},
 {50.0f,47.619f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch123st1[] =
{
 {54.7619f,114.286f},
 {50.0f,104.762f},
 {50.0f,95.2381f},
 {54.7619f,85.7143f},
 {59.5238f,80.9524f},
 {64.2857f,71.4286f},
 {64.2857f,61.9048f},
 {59.5238f,52.381f},
 {40.4762f,42.8571f},
 {59.5238f,33.3333f},
 {64.2857f,23.8095f},
 {64.2857f,14.2857f},
 {59.5238f,4.7619f},
 {54.7619f,0.0f},
 {50.0f,-9.5238f},
 {50.0f,-19.0476f},
 {54.7619f,-28.5714f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch123st2[] =
{
 {50.0f,38.0952f},
 {59.5238f,28.5714f},
 {59.5238f,19.0476f},
 {54.7619f,9.5238f},
 {50.0f,4.7619f},
 {45.2381f,-4.7619f},
 {45.2381f,-14.2857f},
 {50.0f,-23.8095f},
 {54.7619f,-28.5714f},
 {64.2857f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch123st[] =
{
 {10,StrokeMonoRoman_ch123st0},
 {17,StrokeMonoRoman_ch123st1},
 {10,StrokeMonoRoman_ch123st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch123 = {104.762f,3,StrokeMonoRoman_ch123st};

/* char: 0x7c */

static const SFG_StrokeVertex StrokeMonoRoman_ch124st0[] =
{
 {52.381f,119.048f},
 {52.381f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch124st[] =
{
 {2,StrokeMonoRoman_ch124st0}
};

static const SFG_StrokeChar StrokeMonoRoman_ch124 = {104.762f,1,StrokeMonoRoman_ch124st};

/* char: 0x7d */

static const SFG_StrokeVertex StrokeMonoRoman_ch125st0[] =
{
 {40.4762f,119.048f},
 {50.0f,114.286f},
 {54.7619f,109.524f},
 {59.5238f,100.0f},
 {59.5238f,90.4762f},
 {54.7619f,80.9524f},
 {50.0f,76.1905f},
 {45.2381f,66.6667f},
 {45.2381f,57.1429f},
 {54.7619f,47.619f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch125st1[] =
{
 {50.0f,114.286f},
 {54.7619f,104.762f},
 {54.7619f,95.2381f},
 {50.0f,85.7143f},
 {45.2381f,80.9524f},
 {40.4762f,71.4286f},
 {40.4762f,61.9048f},
 {45.2381f,52.381f},
 {64.2857f,42.8571f},
 {45.2381f,33.3333f},
 {40.4762f,23.8095f},
 {40.4762f,14.2857f},
 {45.2381f,4.7619f},
 {50.0f,0.0f},
 {54.7619f,-9.5238f},
 {54.7619f,-19.0476f},
 {50.0f,-28.5714f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch125st2[] =
{
 {54.7619f,38.0952f},
 {45.2381f,28.5714f},
 {45.2381f,19.0476f},
 {50.0f,9.5238f},
 {54.7619f,4.7619f},
 {59.5238f,-4.7619f},
 {59.5238f,-14.2857f},
 {54.7619f,-23.8095f},
 {50.0f,-28.5714f},
 {40.4762f,-33.3333f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch125st[] =
{
 {10,StrokeMonoRoman_ch125st0},
 {17,StrokeMonoRoman_ch125st1},
 {10,StrokeMonoRoman_ch125st2}
};

static const SFG_StrokeChar StrokeMonoRoman_ch125 = {104.762f,3,StrokeMonoRoman_ch125st};

/* char: 0x7e */

static const SFG_StrokeVertex StrokeMonoRoman_ch126st0[] =
{
 {9.5238f,28.5714f},
 {9.5238f,38.0952f},
 {14.2857f,52.381f},
 {23.8095f,57.1429f},
 {33.3333f,57.1429f},
 {42.8571f,52.381f},
 {61.9048f,38.0952f},
 {71.4286f,33.3333f},
 {80.9524f,33.3333f},
 {90.4762f,38.0952f},
 {95.2381f,47.619f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch126st1[] =
{
 {9.5238f,38.0952f},
 {14.2857f,47.619f},
 {23.8095f,52.381f},
 {33.3333f,52.381f},
 {42.8571f,47.619f},
 {61.9048f,33.3333f},
 {71.4286f,28.5714f},
 {80.9524f,28.5714f},
 {90.4762f,33.3333f},
 {95.2381f,47.619f},
 {95.2381f,57.1429f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch126st[] =
{
 {11,StrokeMonoRoman_ch126st0},
 {11,StrokeMonoRoman_ch126st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch126 = {104.762f,2,StrokeMonoRoman_ch126st};

/* char: 0x7f */

static const SFG_StrokeVertex StrokeMonoRoman_ch127st0[] =
{
 {71.4286f,100.0f},
 {33.3333f,-33.3333f}
};

static const SFG_StrokeVertex StrokeMonoRoman_ch127st1[] =
{
 {47.619f,66.6667f},
 {33.3333f,61.9048f},
 {23.8095f,52.381f},
 {19.0476f,38.0952f},
 {19.0476f,23.8095f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {47.619f,0.0f},
 {57.1428f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,28.5714f},
 {85.7143f,42.8571f},
 {80.9524f,52.381f},
 {71.4286f,61.9048f},
 {57.1428f,66.6667f},
 {47.619f,66.6667f}
};

static const SFG_StrokeStrip StrokeMonoRoman_ch127st[] =
{
 {2,StrokeMonoRoman_ch127st0},
 {17,StrokeMonoRoman_ch127st1}
};

static const SFG_StrokeChar StrokeMonoRoman_ch127 = {104.762f,2,StrokeMonoRoman_ch127st};

static const SFG_StrokeChar *StrokeMonoRoman_chars[] =
{
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 &StrokeMonoRoman_ch32, &StrokeMonoRoman_ch33, &StrokeMonoRoman_ch34, &StrokeMonoRoman_ch35, &StrokeMonoRoman_ch36, &StrokeMonoRoman_ch37, &StrokeMonoRoman_ch38, &StrokeMonoRoman_ch39,
 &StrokeMonoRoman_ch40, &StrokeMonoRoman_ch41, &StrokeMonoRoman_ch42, &StrokeMonoRoman_ch43, &StrokeMonoRoman_ch44, &StrokeMonoRoman_ch45, &StrokeMonoRoman_ch46, &StrokeMonoRoman_ch47,
 &StrokeMonoRoman_ch48, &StrokeMonoRoman_ch49, &StrokeMonoRoman_ch50, &StrokeMonoRoman_ch51, &StrokeMonoRoman_ch52, &StrokeMonoRoman_ch53, &StrokeMonoRoman_ch54, &StrokeMonoRoman_ch55,
 &StrokeMonoRoman_ch56, &StrokeMonoRoman_ch57, &StrokeMonoRoman_ch58, &StrokeMonoRoman_ch59, &StrokeMonoRoman_ch60, &StrokeMonoRoman_ch61, &StrokeMonoRoman_ch62, &StrokeMonoRoman_ch63,
 &StrokeMonoRoman_ch64, &StrokeMonoRoman_ch65, &StrokeMonoRoman_ch66, &StrokeMonoRoman_ch67, &StrokeMonoRoman_ch68, &StrokeMonoRoman_ch69, &StrokeMonoRoman_ch70, &StrokeMonoRoman_ch71,
 &StrokeMonoRoman_ch72, &StrokeMonoRoman_ch73, &StrokeMonoRoman_ch74, &StrokeMonoRoman_ch75, &StrokeMonoRoman_ch76, &StrokeMonoRoman_ch77, &StrokeMonoRoman_ch78, &StrokeMonoRoman_ch79,
 &StrokeMonoRoman_ch80, &StrokeMonoRoman_ch81, &StrokeMonoRoman_ch82, &StrokeMonoRoman_ch83, &StrokeMonoRoman_ch84, &StrokeMonoRoman_ch85, &StrokeMonoRoman_ch86, &StrokeMonoRoman_ch87,
 &StrokeMonoRoman_ch88, &StrokeMonoRoman_ch89, &StrokeMonoRoman_ch90, &StrokeMonoRoman_ch91, &StrokeMonoRoman_ch92, &StrokeMonoRoman_ch93, &StrokeMonoRoman_ch94, &StrokeMonoRoman_ch95,
 &StrokeMonoRoman_ch96, &StrokeMonoRoman_ch97, &StrokeMonoRoman_ch98, &StrokeMonoRoman_ch99, &StrokeMonoRoman_ch100, &StrokeMonoRoman_ch101, &StrokeMonoRoman_ch102, &StrokeMonoRoman_ch103,
 &StrokeMonoRoman_ch104, &StrokeMonoRoman_ch105, &StrokeMonoRoman_ch106, &StrokeMonoRoman_ch107, &StrokeMonoRoman_ch108, &StrokeMonoRoman_ch109, &StrokeMonoRoman_ch110, &StrokeMonoRoman_ch111,
 &StrokeMonoRoman_ch112, &StrokeMonoRoman_ch113, &StrokeMonoRoman_ch114, &StrokeMonoRoman_ch115, &StrokeMonoRoman_ch116, &StrokeMonoRoman_ch117, &StrokeMonoRoman_ch118, &StrokeMonoRoman_ch119,
 &StrokeMonoRoman_ch120, &StrokeMonoRoman_ch121, &StrokeMonoRoman_ch122, &StrokeMonoRoman_ch123, &StrokeMonoRoman_ch124, &StrokeMonoRoman_ch125, &StrokeMonoRoman_ch126, &StrokeMonoRoman_ch127
};

SFG_StrokeFont fgStrokeMonoRoman = {"MonoRoman",128,152.381f,StrokeMonoRoman_chars};
